# Cree un volumen
# Cree una red, con la subnet 172.100.0.0/16
# Cree un contendor, basado en la imagen de ubuntu:22.04
# Se cree de forma interactiva (-i -t)
# Tenga la red creada anteriormente 
# Tenga la IP 127.100.0.100
# Mapee el puerto 8080 de mi máquina al 80 de dentro
# tenga el volumen creado anteriormente en la carpeta /app/data
# docker-compose up -d
# docker-compose down


services:
  mi-mongo:
    image: mongo:latest
    container_name: mi-mongo
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    hostname: mi-mongo
    volumes:
      - ./mi-volumen:/data/db/
    networks:
      - mi-red
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=pass 

  mi-mongo-express:
    image: mongo-express:latest
    container_name: mi-mongo-express
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    hostname: mi-mongo-express
    ports:
      - 80:8081
    volumes:
      - ./mi-volumen:/data/db/
    networks:
      - mi-red
    environment:
      - ME_CONFIG_MONGODB_SERVER=mi-mongo 
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
networks:
  mi-red:
volumes:
  mi-volumen:

